# Rose Pine Theme Configuration
set -g @rose_pine_variant 'main' # Options: 'main', 'moon', 'dawn'

# Status bar configuration
set -g status-right-length 100
set -g status-left-length 100
set -g @rose_pine_date_time '%Y-%m-%d %H:%M:%S'
set -g status-interval 1
